version: '3.8'  # Specify the Docker Compose file format version

services:
  url-shortener:
      build:
        context: .             # Set the context to the root level
        dockerfile: url-shortener/Dockerfile  # Specify the Dockerfile path
      ports:
        - "8005:8005"
      volumes:
        - .:/url-shortener  # Bind mount aggregator directory into the container
      depends_on:
        - db

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: url_shortener_db  # Name of the container
    restart: always  # Restart the container automatically
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db 
    ports:
      - "5432:5432"  # Map the host port to the container port
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data across container restarts

volumes:
  pgdata:  # Named volume for PostgreSQL data
